apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: ltp1405/udagram-api-feed
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: config-env
              optional: false
          - secretRef:
              name: env-secret
              optional: false # same as default; "mysecret" must exist
                              # and include a key named "username"
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws/"
          readOnly: true        
      restartPolicy: Always
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret 
