apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: udagram-api-user
        image: ltp1405/udagram-api-user
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: config-env
          - secretRef:
              name: env-secret
              optional: false # same as default; "mysecret" must exist
                              # and include a key named "username"
