language: node_js
node_js:
  - 16

services:
  - docker

# Pre-testing installs
install:
  - echo "Installing"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-user ltp1405/udagram-api-user:latest
  - docker tag udagram-api-feed ltp1405/udagram-api-feed:latest
  - docker tag udagram-reverseproxy ltp1405/udagram-reverseproxy:latest
  - docker tag udagram-frontend ltp1405/udagram-frontend:latest

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push udagram-api-user
  - docker push udagram-api-feed
  - docker push udagram-reverseproxy
  - docker push udagram-frontend
